# Use root/example as user/password credentials
version: "3"
services:
  redis:
    image: redis:latest
    container_name: core_app_redis
    restart: always
    ports:
      - 6379:6379
  mongo:
    image: mongo:latest
    container_name: core_app_mongo
    restart: always
    volumes:
      - 'mongo:/data/db'
    ports:
      - 27017:27017
  api-server:
    build:
      context: .
    container_name: core_app_api
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      - DB_URL=mongo/Platform_Core
      - DB_USER=
      - DB_PASSWORD=
      - REDIS_URL=redis
      - PORT=3000
volumes:
  mongo:
